[tool.poetry]
name = "mysql2json"
version = "0.1.0"
description = ""
authors = ["Arturo M <github.com/arturom>"]

[tool.poetry.dependencies]
python = "^3.8"
PyMySQL = "^0.9.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
